### ISSUE TITLE
📚 Documentation: NO README.md for To Do App With Appwrite And Flutter Videos

### ISSUE THREAD

**Issue by DestinedCodes** [appwrite/octernships#13]
### 💭 Description

I applied for the To Do App With Appwrite And Flutter Videos octernship project. ever since application. I haven't been able to find a README.md file which should contain information about the assignment. The deadline is approaching please help me fix this.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by tessamero** [comment]
You can find the project information here:

https://github.com/appwrite/octernships/blob/main/devrel_task1.md


I may have structured it wrong but I think it's too late to change all the files/folder structure. Happy to hear your thoughts.

**Comment by DestinedCodes** [comment]
Thanks a lot. If I complete this project can I consider contributing to others as well?

**Comment by tessamero** [comment]
@DestinedCodes yes you may :)

I'm going to update all the md files and structure as i was supposed to create template files and readmes for each and including it in github classrooms :) SO i will close this issue now that I know what the problem was :)
