### ISSUE TITLE
📚 Documentation: 

### ISSUE THREAD

**Issue by antonio-pedro99** [appwrite/octernships#16]
### 💭 Description

Engineering Task 1 - Add-on packages: UI Helper libraries for web and other platforms to allow developers to interact with the Appwrite API seamlessly.

Do we have to integrate authentication with multiple providers or with Email/Google enough for showcasing?

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by Nandini99-git** [comment]
I would like to work on this issue. Please assign me.

**Comment by christyjacob4** [comment]
Hello @antonio-pedro99  this repository is now archived. All further communication regarding the octernship will he done on [GitHub Discussions](https://github.com/orgs/appwrite-octernship/discussions). Please post your query there.
