### ISSUE TITLE
🚀 Feature: Allow react native for engineering task 1

### ISSUE THREAD

**Issue by Neel-shetty** [appwrite/octernships#17]
### 🔖 Feature description

UI helper library can be made for react native as well, would that submission be accepted?

### 🎤 Pitch

I selected engineering task 1 as my project on the octernship website, I am not sure if you will accept submissions using react native, please provide more details regarding it.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
Hello @Neel-shetty this repository is now archived. All further communication regarding the octernship will he done on [GitHub Discussions](https://github.com/orgs/appwrite-octernship/discussions). Please post your query there.
