### ISSUE TITLE
Can I use Android (Kotlin) instead of Flutter to develop the to-do app with Appwrite?

### ISSUE THREAD

**Issue by AbhiiVops** [appwrite/octernships#9]
Dear Maintainer,

I hope this message finds you well. I have been following your tutorial series on creating a to-do app with Appwrite and Flutter, and I appreciate the effort you have put into creating this resource for new developers. However, I am wondering if it would be possible to use Android (Kotlin) instead of Flutter to develop the app?

While I understand that the tutorial is specifically focused on using Flutter, I have more experience with Android development and I would like to use Kotlin instead. I believe that the functionality of the app should be achievable using Android, and I am willing to work through any potential issues that may arise during development.

If it is possible to use Android instead of Flutter, I would greatly appreciate any guidance or resources you can provide to help me get started. If not, I completely understand and I will continue to follow along with the tutorial using Flutter.

Thank you for your time and consideration.

Best regards,
**Abhishek Bhattacharjee**

**Comment by tessamero** [comment]
Hi Abhishek, I will allow this with you. Just make a note with your video and app submission. :)
